version: "3"

services:
  mongo:
    image: mongo:4.0.18-xenial
    volumes:
      - ./data/mongo:/data/db

  app:
    build:
      context: .
      dockerfile: ./docker/development.dockerfile
    depends_on:
        - mongo
    command: yarn dev
    ports:
      - 3461:3461

    volumes:
      - .:/usr/src/app
