version: 2

defaults: &defaults
  working_directory: ~/repo
  machine: true

jobs:
  test:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: Setup project
          command: |
            make build
      - run:
          name: Lint project
          command: |
            make lint

      - run:
          name: Test project
          command: |
            make test

workflows:
  version: 2
  test:
    jobs:
      - test
